languageCode = "en-us"
title = "Лис.пресс"
theme = "hugo-lis"
baseurl = "localhost:1313"
newContentEditor = "vim"
pygmentsStyle = "native"
googleAnalytics = "UA-74408540-1"

[params]
  maintitle = "Лис.пресс"
  mainsubtitle = "Эксперименты с business-aware разработкой"
  description = "Лис.пресс — платформа для обмена опытом в создании и продвижении интернет-проектов"
  author = "Александр Елисеев"
  authoremail = "eliseealex@gmail.com"
  enableTableOfContent = true
  enablePath = true
  enableAnalytic = false