languageCode = "en-us"
title = "Лис.пресс"
theme = "hugo-lis"
baseurl = "localhost:1313"

[params]
  maintitle = "Лис.пресс"
  mainsubtitle = "Эксперименты с business-aware разработкой"
  description = "Лис.пресс — платформа для обмена опыта в создании и продвижении интернет-проектов"
  author = "Александр Елисеев"