languageCode = "en-us"
title = "Блог Александра Елисеева"
theme = "hugo-lis"
baseurl = "http://eliseealex.me"
newContentEditor = "vim"
pygmentsStyle = "native"
googleAnalytics = "UA-74408540-2"

[params]
  maintitle = "EliseeAlex.me"
  mainsubtitle = "Блог о business-aware разработке"
  description = "**Пишите**, я открыт для критики и предложений."
  metaKeywords = "Business-aware разработка, open-source, lean startup, маркетинг, ux, блог, примеры"

  authorEmail = "eliseealex@gmail.com"
  authorTwitter = "eliseealex"

  enableTableOfContent = false
  enablePath = true
  enableAnalytic = true

  yandexMetrika = "37008430"
