languageCode = "en-us"
title = "Блог Александра Елисеева"
theme = "hugo-lis"
baseurl = "//eliseealex.me"
newContentEditor = "vim"
pygmentsStyle = "native"
googleAnalytics = "UA-74408540-1"

[params]
  maintitle = "EliseeAlex.me"
  mainsubtitle = "Блог о business-aware разработке"
  description = "[EliseeAlex.me](//eliseealex.me) — мой личный блог.<br> **Пишите**, я открыт для критики и предложений."
  metaKeywords = "Business-aware разработка, open-source, lean startup, маркетинг, ux, блог, примеры"

  authorEmail = "eliseealex@gmail.com"
  authorTwitter = "eliseealex"

  enableTableOfContent = false
  enablePath = true
  enableAnalytic = false

  yandexMetrika = "36272730"
