languageCode = "en-us"
title = "Блог Александра Елисеева"
theme = "hugo-lis"
baseurl = "http://eliseealex.me"
newContentEditor = "vim"
googleAnalytics = "UA-74408540-2"

pygmentsStyle = "friendly"

[params]
  maintitle = "EliseeAlex.me"
  mainsubtitle = "Блог о business-aware разработке"
  description = "Я открыт для критики и предложений. Готов помочь хорошим людям. **Пишите**!"
  metaKeywords = "Business-aware разработка, open-source, lean startup, маркетинг, ux, блог, примеры"

  authorEmail = "eliseealex@gmail.com"
  authorTwitter = "eliseealex"
  authorGithub = "eliseealex"

  enableTableOfContent = false
  enablePath = true
  enableAnalytic = true

  yandexMetrika = "37008430"

  highlightJs = true
